package documentTreeModel.implementation;

import java.util.UUID;

import documentTreeModel.interfaces.IDocumentBoxMessageResponse;


//message is beeing generated by the PeerBox, to notify the DocumentBox about the migration response of one send message
public class DocumentBoxMessageDocumentBoxMigratedResponse implements IDocumentBoxMessageResponse
{
	long _targetDocumentBox =0;
	long _sourcePeerBox = 0;
	Object _failedMessage; 
	
	UUID _requestUUID;	
	@Override
	public UUID GetMessageGuid() {
			return _requestUUID;
	}
	
	public DocumentBoxMessageDocumentBoxMigratedResponse(long migratedToTarget, Object failedMessage, long sourcePeerBox)
	{
		_targetDocumentBox = migratedToTarget;
		_failedMessage = failedMessage;
		_sourcePeerBox = sourcePeerBox;
		_requestUUID  = UUID.randomUUID();
	}
	@Override
	public DocumentBoxMessageType GetMessageType() 
	{
		return DocumentBoxMessageType.MigratedResponse;
	}
	
	
	public long GetSourcePeerBox()
	{
		return _sourcePeerBox;
	}
	
	public Object GetFailedMessage() 
	{
		return _failedMessage;
	}
	
	public long MigratedToPeerBoxTarget() {

		return _targetDocumentBox;
	}
	@Override
	public ResponseTypeDocumentBox GetResponseType() 
	{
		return ResponseTypeDocumentBox.NOK;
	}
}
